export class EnemyTypes {
    static BIG_BOMB = 'BIG_BOMB';
    static WALKER = 'WALKER';
    static POUNDER = 'POUNDER';
    static BOMB = 'BOMB';
    static ROCKET = 'ROCKET';
    static TURRET = 'TURRET';
    static TOWER = 'TOWER';
    static TANK = 'TANK';
    static BOSS = 'BOSS';
    static HEAVY = 'HEAVY';
    static CHASER = 'CHASER';
    static SENTRY = 'SENTRY';
    static DUMPER = 'DUMPER';
    static POPPER = 'POPPER';
    static BOMBER = 'BOMBER';
    static ZAMBONEY = 'ZAMBONEY';
    static FINAL_BOSS = 'FINAL_BOSS';
}
